version: '3.7'
services:
  web:
    build: ./meteo/meteo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./meteo/meteo:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - .data:/data/db
