version: '3.7'
services:
  web:
    build: .
    container_name: meteo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./meteo:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - .data:/data/db
